Fix compilation dependencies on Fedora Linux
santiagocezar/rsdkv5-decomp-docs pull request #1
Opened 2022-09-07 22:53 UTC by TheAgamer554

Adds missing g++ dependency for compiling on fedora

2022-09-08 16:16 UTC, santiagocezar requested changes

2022-09-08 16:16 UTC, santiagocezar commented on Linux.md
> +sudo dnf install glew-devel glfw-devel libtheora-devel zlib-devel SDL2-devel g--
g--?

2022-09-08 16:20 UTC, santiagocezar commented
Not sure what g-- is but it's surely not a compiler. Also that's missing on the 3 distros not just Fedora

2022-09-10 01:19 UTC, TheAgamer554 commented on Linux.md
> +sudo dnf install glew-devel glfw-devel libtheora-devel zlib-devel SDL2-devel g--
typo lol

2022-09-15 14:41 UTC, santiagocezar approved these changes

2022-09-15 14:41 UTC, merged